from pydantic import BaseModel, Field

AUTOPOPULATED = "Autopopulated"

from typing import List
import psycopg2

class ADMISSION(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    SUBJECT_ID: int = AUTOPOPULATED
    HADM_ID: int = AUTOPOPULATED
    ADMITTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    DISCHTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    DEATHTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    ADMISSION_TYPE: str = AUTOPOPULATED  # VARCHAR(50)
    ADMISSION_LOCATION: str = AUTOPOPULATED  # VARCHAR(50)
    DISCHARGE_LOCATION: str = AUTOPOPULATED  # VARCHAR(50)
    INSURANCE: str = AUTOPOPULATED  # VARCHAR(255)
    LANGUAGE: str = AUTOPOPULATED  # VARCHAR(10)
    RELIGION: str = AUTOPOPULATED  # VARCHAR(50)
    MARITAL_STATUS: str = AUTOPOPULATED  # VARCHAR(50)
    ETHNICITY: str = AUTOPOPULATED  # VARCHAR(200)
    EDREGTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    EDOUTTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    DIAGNOSIS: str = AUTOPOPULATED  # VARCHAR(300)
    HOSPITAL_EXPIRE_FLAG: int = AUTOPOPULATED  # TINYINT
    HAS_CHARTEVENTS_DATA: int = AUTOPOPULATED  # TINYINT

class CALLOUT(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    SUBJECT_ID: int = AUTOPOPULATED
    HADM_ID: int = AUTOPOPULATED
    SUBMIT_WARDID: int = AUTOPOPULATED
    SUBMIT_CAREUNIT: str = AUTOPOPULATED  # VARCHAR(15)
    CURR_WARDID: int = AUTOPOPULATED
    CURR_CAREUNIT: str = AUTOPOPULATED  # VARCHAR(15)
    CALLOUT_WARDID: int = AUTOPOPULATED
    CALLOUT_SERVICE: str = AUTOPOPULATED  # VARCHAR(10)
    REQUEST_TELE: int = AUTOPOPULATED  # SMALLINT
    REQUEST_RESP: int = AUTOPOPULATED  # SMALLINT
    REQUEST_CDIFF: int = AUTOPOPULATED  # SMALLINT
    REQUEST_MRSA: int = AUTOPOPULATED  # SMALLINT
    REQUEST_VRE: int = AUTOPOPULATED  # SMALLINT
    CALLOUT_STATUS: str = AUTOPOPULATED  # VARCHAR(20)
    CALLOUT_OUTCOME: str = AUTOPOPULATED  # VARCHAR(20)
    DISCHARGE_WARDID: int = AUTOPOPULATED
    ACKNOWLEDGE_STATUS: str = AUTOPOPULATED  # VARCHAR(20)
    CREATETIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    UPDATETIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    ACKNOWLEDGETIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    OUTCOMETIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    FIRSTRESERVATIONTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    CURRENTRESERVATIONTIME: str = AUTOPOPULATED  # TIMESTAMP(0)

class CAREGIVERS(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    CGID: int = AUTOPOPULATED
    LABEL: str = AUTOPOPULATED  # VARCHAR(15)
    DESCRIPTION: str = AUTOPOPULATED  # VARCHAR(30)

class CHARTEVENTS(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    SUBJECT_ID: int = AUTOPOPULATED  # NUMBER(7,0)
    HADM_ID: int = AUTOPOPULATED  # NUMBER(7,0)
    ICUSTAY_ID: int = AUTOPOPULATED  # NUMBER(7,0)
    ITEMID: int = AUTOPOPULATED  # NUMBER(7,0)
    CHARTTIME: str = AUTOPOPULATED  # DATE
    STORETIME: str = AUTOPOPULATED  # DATE
    CGID: int = AUTOPOPULATED  # NUMBER(7,0)
    VALUE: str = AUTOPOPULATED  # VARCHAR2(200 BYTE)
    VALUENUM: float = AUTOPOPULATED  # NUMBER
    VALUEUOM: str = AUTOPOPULATED  # VARCHAR2(20 BYTE)
    WARNING: int = AUTOPOPULATED  # NUMBER(1,0)
    ERROR: int = AUTOPOPULATED  # NUMBER(1,0)
    RESULTSTATUS: str = AUTOPOPULATED  # VARCHAR2(20 BYTE)
    STOPPED: str = AUTOPOPULATED  # VARCHAR2(20 BYTE)

class CPTEVENTS(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    SUBJECT_ID: int = AUTOPOPULATED
    HADM_ID: int = AUTOPOPULATED
    COSTCENTER: str = AUTOPOPULATED  # VARCHAR(10)
    CHARTDATE: str = AUTOPOPULATED  # TIMESTAMP(0)
    CPT_CD: str = AUTOPOPULATED  # VARCHAR(10)
    CPT_NUMBER: int = AUTOPOPULATED
    CPT_SUFFIX: str = AUTOPOPULATED  # VARCHAR(5)
    TICKET_ID_SEQ: int = AUTOPOPULATED
    SECTIONHEADER: str = AUTOPOPULATED  # VARCHAR(50)
    SUBSECTIONHEADER: str = AUTOPOPULATED  # VARCHAR(300)
    DESCRIPTION: str = AUTOPOPULATED  # VARCHAR(200)

class D_CPT(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    CATEGORY: int = AUTOPOPULATED  # SMALLINT
    SECTIONRANGE: str = AUTOPOPULATED  # VARCHAR(100)
    SECTIONHEADER: str = AUTOPOPULATED  # VARCHAR(50)
    SUBSECTIONRANGE: str = AUTOPOPULATED  # VARCHAR(100)
    SUBSECTIONHEADER: str = AUTOPOPULATED  # VARCHAR(300)
    CODESUFFIX: str = AUTOPOPULATED  # VARCHAR(5)
    MINCODEINSUBSECTION: int = AUTOPOPULATED
    MAXCODEINSUBSECTION: int = AUTOPOPULATED

class D_ICD_DIAGNOSES(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    ICD9_CODE: str = AUTOPOPULATED  # VARCHAR(10)
    SHORT_TITLE: str = AUTOPOPULATED  # VARCHAR(50)
    LONG_TITLE: str = AUTOPOPULATED  # VARCHAR(300)

class D_ICD_PROCEDURES(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    ICD9_CODE: str = AUTOPOPULATED  # VARCHAR(10)
    SHORT_TITLE: str = AUTOPOPULATED  # VARCHAR(50)
    LONG_TITLE: str = AUTOPOPULATED  # VARCHAR(300)

class D_ITEMS(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    ITEMID: int = AUTOPOPULATED
    LABEL: str = AUTOPOPULATED  # VARCHAR(200)
    ABBREVIATION: str = AUTOPOPULATED  # VARCHAR(100)
    DBSOURCE: str = AUTOPOPULATED  # VARCHAR(20)
    LINKSTO: str = AUTOPOPULATED  # VARCHAR(50)
    CATEGORY: str = AUTOPOPULATED  # VARCHAR(100)
    UNITNAME: str = AUTOPOPULATED  # VARCHAR(100)
    PARAM_TYPE: str = AUTOPOPULATED  # VARCHAR(30)
    CONCEPTID: int = AUTOPOPULATED

class D_LABITEMS(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    ITEMID: int = AUTOPOPULATED
    LABEL: str = AUTOPOPULATED  # VARCHAR(100)
    FLUID: str = AUTOPOPULATED  # VARCHAR(100)
    CATEGORY: str = AUTOPOPULATED  # VARCHAR(100)
    LOINC_CODE: str = AUTOPOPULATED  # VARCHAR(100)

class DATETIMEEVENTS(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    SUBJECT_ID: int = AUTOPOPULATED
    HADM_ID: int = AUTOPOPULATED
    ICUSTAY_ID: int = AUTOPOPULATED
    ITEMID: int = AUTOPOPULATED
    CHARTTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    STORETIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    CGID: int = AUTOPOPULATED
    VALUE: str = AUTOPOPULATED  # TIMESTAMP(0)
    VALUEUOM: str = AUTOPOPULATED  # VARCHAR(50)
    WARNING: int = AUTOPOPULATED  # SMALLINT
    ERROR: int = AUTOPOPULATED  # SMALLINT
    RESULTSTATUS: str = AUTOPOPULATED  # VARCHAR(50)
    STOPPED: str = AUTOPOPULATED  # VARCHAR(50)

class DIAGNOSES_ICD(BaseModel):
    ROW_ID: int = AUTOPOPULATED  # not null
    SUBJECT_ID: int = AUTOPOPULATED  # not null
    HADM_ID: int = AUTOPOPULATED  # not null
    SEQ_NUM: int = AUTOPOPULATED
    ICD9_CODE: str = AUTOPOPULATED  # VARCHAR(10)

class DRGCODES(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    SUBJECT_ID: int = AUTOPOPULATED
    HADM_ID: int = AUTOPOPULATED
    DRG_TYPE: str = AUTOPOPULATED  # VARCHAR(20)
    DRG_CODE: str = AUTOPOPULATED  # VARCHAR(20)
    DESCRIPTION: str = AUTOPOPULATED  # VARCHAR(300)
    DRG_SEVERITY: int = AUTOPOPULATED  # SMALLINT
    DRG_MORTALITY: int = AUTOPOPULATED  # SMALLINT

class ICUSTAYS(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    SUBJECT_ID: int = AUTOPOPULATED
    HADM_ID: int = AUTOPOPULATED
    ICUSTAY_ID: int = AUTOPOPULATED
    DBSOURCE: str = AUTOPOPULATED  # VARCHAR(20)
    FIRST_CAREUNIT: str = AUTOPOPULATED  # VARCHAR(20)
    LAST_CAREUNIT: str = AUTOPOPULATED  # VARCHAR(20)
    FIRST_WARDID: int = AUTOPOPULATED  # SMALLINT
    LAST_WARDID: int = AUTOPOPULATED  # SMALLINT
    INTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    OUTTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    LOS: float = AUTOPOPULATED  # DOUBLE

class INPUTEVENTS_CV(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    SUBJECT_ID: int = AUTOPOPULATED
    HADM_ID: int = AUTOPOPULATED
    ICUSTAY_ID: int = AUTOPOPULATED
    CHARTTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    ITEMID: int = AUTOPOPULATED
    AMOUNT: float = AUTOPOPULATED  # DOUBLE PRECISION
    AMOUNTUOM: str = AUTOPOPULATED  # VARCHAR(30)
    RATE: float = AUTOPOPULATED  # DOUBLE PRECISION
    RATEUOM: str = AUTOPOPULATED  # VARCHAR(30)
    STORETIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    CGID: int = AUTOPOPULATED  # BIGINT
    ORDERID: int = AUTOPOPULATED  # BIGINT
    LINKORDERID: int = AUTOPOPULATED  # BIGINT
    STOPPED: str = AUTOPOPULATED  # VARCHAR(30)
    NEWBOTTLE: int = AUTOPOPULATED
    ORIGINALAMOUNT: float = AUTOPOPULATED  # DOUBLE PRECISION
    ORIGINALAMOUNTUOM: str = AUTOPOPULATED  # VARCHAR(30)
    ORIGINALROUTE: str = AUTOPOPULATED  # VARCHAR(30)
    ORIGINALRATE: float = AUTOPOPULATED  # DOUBLE PRECISION
    ORIGINALRATEUOM: str = AUTOPOPULATED  # VARCHAR(30)
    ORIGINALSITE: str = AUTOPOPULATED  # VARCHAR(30)

class INPUTEVENTS_MV(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    SUBJECT_ID: int = AUTOPOPULATED
    HADM_ID: int = AUTOPOPULATED
    ICUSTAY_ID: int = AUTOPOPULATED
    STARTTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    ENDTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    ITEMID: int = AUTOPOPULATED
    AMOUNT: float = AUTOPOPULATED  # DOUBLE PRECISION
    AMOUNTUOM: str = AUTOPOPULATED  # VARCHAR(30)
    RATE: float = AUTOPOPULATED  # DOUBLE PRECISION
    RATEUOM: str = AUTOPOPULATED  # VARCHAR(30)
    STORETIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    CGID: int = AUTOPOPULATED  # BIGINT
    ORDERID: int = AUTOPOPULATED  # BIGINT
    LINKORDERID: int = AUTOPOPULATED  # BIGINT
    ORDERCATEGORYNAME: str = AUTOPOPULATED  # VARCHAR(100)
    SECONDARYORDERCATEGORYNAME: str = AUTOPOPULATED  # VARCHAR(100)
    ORDERCOMPONENTTYPEDESCRIPTION: str = AUTOPOPULATED  # VARCHAR(200)
    ORDERCATEGORYDESCRIPTION: str = AUTOPOPULATED  # VARCHAR(50)
    PATIENTWEIGHT: float = AUTOPOPULATED  # DOUBLE PRECISION
    TOTALAMOUNT: float = AUTOPOPULATED  # DOUBLE PRECISION
    TOTALAMOUNTUOM: str = AUTOPOPULATED  # VARCHAR(50)
    ISOPENBAG: int = AUTOPOPULATED  # SMALLINT
    CONTINUEINNEXTDEPT: int = AUTOPOPULATED  # SMALLINT
    CANCELREASON: int = AUTOPOPULATED  # SMALLINT
    STATUSDESCRIPTION: str = AUTOPOPULATED  # VARCHAR(30)
    COMMENTS_STATUS: str = AUTOPOPULATED  # VARCHAR(30)
    COMMENTS_TITLE: str = AUTOPOPULATED  # VARCHAR(100)
    COMMENTS_DATE: str = AUTOPOPULATED  # TIMESTAMP(0)
    ORIGINALAMOUNT: float = AUTOPOPULATED  # DOUBLE PRECISION
    ORIGINALRATE: float = AUTOPOPULATED  # DOUBLE PRECISION

class LABEVENTS(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    SUBJECT_ID: int = AUTOPOPULATED
    HADM_ID: int = AUTOPOPULATED
    ITEMID: int = AUTOPOPULATED
    CHARTTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    VALUE: str = AUTOPOPULATED  # VARCHAR(200)
    VALUENUM: float = AUTOPOPULATED  # DOUBLE PRECISION
    VALUEUOM: str = AUTOPOPULATED  # VARCHAR(20)
    FLAG: str = AUTOPOPULATED  # VARCHAR(20)

class MICROBIOLOGYEVENTS(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    SUBJECT_ID: int = AUTOPOPULATED
    HADM_ID: int = AUTOPOPULATED
    CHARTDATE: str = AUTOPOPULATED  # TIMESTAMP(0)
    CHARTTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    SPEC_ITEMID: int = AUTOPOPULATED
    SPEC_TYPE_DESC: str = AUTOPOPULATED  # VARCHAR(100)
    ORG_ITEMID: int = AUTOPOPULATED
    ORG_NAME: str = AUTOPOPULATED  # VARCHAR(100)
    ISOLATE_NUM: int = AUTOPOPULATED  # SMALLINT
    AB_ITEMID: int = AUTOPOPULATED
    AB_NAME: str = AUTOPOPULATED  # VARCHAR(30)
    DILUTION_TEXT: str = AUTOPOPULATED  # VARCHAR(10)
    DILUTION_COMPARISON: str = AUTOPOPULATED  # VARCHAR(20)
    DILUTION_VALUE: float = AUTOPOPULATED  # DOUBLE PRECISION
    INTERPRETATION: str = AUTOPOPULATED  # VARCHAR(5)

class NOTEEVENTS(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    SUBJECT_ID: int = AUTOPOPULATED
    HADM_ID: int = AUTOPOPULATED
    CHARTDATE: str = AUTOPOPULATED  # TIMESTAMP(0)
    CHARTTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    STORETIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    CATEGORY: str = AUTOPOPULATED  # VARCHAR(50)
    DESCRIPTION: str = AUTOPOPULATED  # VARCHAR(300)
    CGID: int = AUTOPOPULATED
    ISERROR: str = AUTOPOPULATED  # CHAR(1)
    TEXT: str = AUTOPOPULATED  # TEXT

class OUTPUTEVENTS(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    SUBJECT_ID: int = AUTOPOPULATED
    HADM_ID: int = AUTOPOPULATED
    ICUSTAY_ID: int = AUTOPOPULATED
    CHARTTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    ITEMID: int = AUTOPOPULATED
    VALUE: float = AUTOPOPULATED  # DOUBLE PRECISION
    VALUEUOM: str = AUTOPOPULATED  # VARCHAR(30)
    STORETIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    CGID: int = AUTOPOPULATED  # BIGINT
    STOPPED: str = AUTOPOPULATED  # VARCHAR(30)
    NEWBOTTLE: int = AUTOPOPULATED
    ISERROR: int = AUTOPOPULATED  # SMALLINT

class PATIENTS(BaseModel):
    # patient_name: str = AUTOPOPULATED
    SUBJECT_ID: int = AUTOPOPULATED 
    GENDER: int = AUTOPOPULATED 
    DOB: str = AUTOPOPULATED
    DOD: str = AUTOPOPULATED
    DOD_HOSP: str = AUTOPOPULATED
    DOD_SSN: str = AUTOPOPULATED
    EXPIRE_FLAG: int = AUTOPOPULATED

class PRESCRIPTIONS(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    SUBJECT_ID: int = AUTOPOPULATED
    HADM_ID: int = AUTOPOPULATED
    ICUSTAY_ID: int = AUTOPOPULATED
    STARTDATE: str = AUTOPOPULATED  # TIMESTAMP(0)
    ENDDATE: str = AUTOPOPULATED  # TIMESTAMP(0)
    DRUG_TYPE: str = AUTOPOPULATED  # VARCHAR(100)
    DRUG: str = AUTOPOPULATED  # VARCHAR(100)
    DRUG_NAME_POE: str = AUTOPOPULATED  # VARCHAR(100)
    DRUG_NAME_GENERIC: str = AUTOPOPULATED  # VARCHAR(100)
    FORMULARY_DRUG_CD: str = AUTOPOPULATED  # VARCHAR(120)
    GSN: str = AUTOPOPULATED  # VARCHAR(200)
    NDC: str = AUTOPOPULATED  # VARCHAR(120)
    PROD_STRENGTH: str = AUTOPOPULATED  # VARCHAR(120)
    DOSE_VAL_RX: str = AUTOPOPULATED  # VARCHAR(120)
    DOSE_UNIT_RX: str = AUTOPOPULATED  # VARCHAR(120)
    FORM_VAL_DISP: str = AUTOPOPULATED  # VARCHAR(120)
    FORM_UNIT_DISP: str = AUTOPOPULATED  # VARCHAR(120)
    ROUTE: str = AUTOPOPULATED  # VARCHAR(120)

class PROCEDUREEVENTS_MV(BaseModel):
    ROW_ID: int = AUTOPOPULATED  # NOT NULL
    SUBJECT_ID: int = AUTOPOPULATED  # NOT NULL
    HADM_ID: int = AUTOPOPULATED  # NOT NULL
    ICUSTAY_ID: int = AUTOPOPULATED
    STARTTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    ENDTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    ITEMID: int = AUTOPOPULATED
    VALUE: float = AUTOPOPULATED  # DOUBLE PRECISION
    VALUEUOM: str = AUTOPOPULATED  # VARCHAR(30)
    LOCATION: str = AUTOPOPULATED  # VARCHAR(30)
    LOCATIONCATEGORY: str = AUTOPOPULATED  # VARCHAR(30)
    STORETIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    CGID: int = AUTOPOPULATED
    ORDERID: int = AUTOPOPULATED
    LINKORDERID: int = AUTOPOPULATED
    ORDERCATEGORYNAME: str = AUTOPOPULATED  # VARCHAR(100)
    SECONDARYORDERCATEGORYNAME: str = AUTOPOPULATED  # VARCHAR(100)
    ORDERCATEGORYDESCRIPTION: str = AUTOPOPULATED  # VARCHAR(50)
    ISOPENBAG: int = AUTOPOPULATED  # SMALLINT
    CONTINUEINNEXTDEPT: int = AUTOPOPULATED  # SMALLINT
    CANCELREASON: int = AUTOPOPULATED  # SMALLINT
    STATUSDESCRIPTION: str = AUTOPOPULATED  # VARCHAR(30)
    COMMENTS_EDITEDBY: str = AUTOPOPULATED  # VARCHAR(30)
    COMMENTS_CANCELEDBY: str = AUTOPOPULATED  # VARCHAR(30)
    COMMENTS_DATE: str = AUTOPOPULATED  # TIMESTAMP(0)

class PROCEDURES_ICD(BaseModel):
    ROW_ID: int = AUTOPOPULATED  # not null
    SUBJECT_ID: int = AUTOPOPULATED  # not null
    HADM_ID: int = AUTOPOPULATED  # not null
    SEQ_NUM: int = AUTOPOPULATED
    ICD9_CODE: str = AUTOPOPULATED  # VARCHAR(10)

class SERVICES(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    SUBJECT_ID: int = AUTOPOPULATED
    HADM_ID: int = AUTOPOPULATED
    TRANSFERTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    PREV_SERVICE: str = AUTOPOPULATED  # VARCHAR(20)
    CURR_SERVICE: str = AUTOPOPULATED  # VARCHAR(20)

class TRANSFERS(BaseModel):
    ROW_ID: int = AUTOPOPULATED
    SUBJECT_ID: int = AUTOPOPULATED
    HADM_ID: int = AUTOPOPULATED
    ICUSTAY_ID: int = AUTOPOPULATED
    DBSOURCE: str = AUTOPOPULATED  # VARCHAR(20)
    EVENTTYPE: str = AUTOPOPULATED  # VARCHAR(20)
    PREV_CAREUNIT: str = AUTOPOPULATED  # VARCHAR(20)
    CURR_CAREUNIT: str = AUTOPOPULATED  # VARCHAR(20)
    PREV_WARDID: int = AUTOPOPULATED  # SMALLINT
    CURR_WARDID: int = AUTOPOPULATED  # SMALLINT
    INTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    OUTTIME: str = AUTOPOPULATED  # TIMESTAMP(0)
    LOS: int = AUTOPOPULATED  # INT
